import FastHeader from "@/components/FastHeader";
import LotteryEntrance from "@/components/LotteryEntrance";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useMoralis } from "react-moralis";

const inter = Inter({ subsets: ["latin"] });

const supportedChains = ["31337", "5"];

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();
  const chainIdString = chainId ? parseInt(chainId).toString() : "0";

  return (
    <>
      <Head>
        <title>Smart contract lottery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FastHeader />
      {isWeb3Enabled ? (
        <div>
          {supportedChains.includes(chainIdString) ? (
            <div className="flex flex-row ">
              <LotteryEntrance />
            </div>
          ) : (
            <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
          )}
        </div>
      ) : (
        <div>Please connect to a Wallet</div>
      )}
    </>
  );
}
